version: '3'
services:
  daemon:
    image: traefik:1.7
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik.toml:/traefik.toml
      - ./volumes/acme.json:/etc/traefik/acme/acme.json
    command:
      - "--api"
      - "--insecureSkipVerify=true"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=${WEBPROXY_CONF_EMAIL:-user@domain.com}"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=${WEBPROXY_CONF_DOMAIN:-domain.com}"
      - "--docker.watch"
      - "--logLevel=INFO"
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  web:
    external: true
